# Generated by Django 3.2.5 on 2021-07-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='defauult_county',
            new_name='default_county',
        ),
    ]
