# Generated by Django 3.2.5 on 2021-07-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Pieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specalistion', models.CharField(choices=[('OIL', 'Oil paintings'), ('WATER', 'Water paintings'), ('ABSTRACT', 'Abstract'), ('BUILDING', 'Buildings'), ('ANIMAL', 'Animal')], max_length=20)),
                ('art_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.art_pieces')),
            ],
        ),
    ]
