# Generated by Django 3.2.5 on 2021-07-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_pieces',
            name='size',
        ),
        migrations.RemoveField(
            model_name='artwork_cat',
            name='art_piece',
        ),
        migrations.AddField(
            model_name='art_pieces',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gallery.artwork_cat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art_pieces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='art_pieces',
            name='size_heigth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='art_pieces',
            name='size_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='artwork_cat',
            name='specalistion',
            field=models.CharField(choices=[('PPLE', 'People'), ('OBJCT', 'Objects'), ('ABST', 'Abstract'), ('BUIL', 'Buildings'), ('LOCA', 'Location'), ('ANIM', 'Animal')], max_length=20),
        ),
    ]
