# Generated by Django 3.2.5 on 2021-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210714_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art_pieces',
            name='image',
        ),
        migrations.AlterField(
            model_name='art_pieces',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
