# Generated by Django 3.2.5 on 2021-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210714_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_pieces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
