# Generated by Django 3.2.5 on 2021-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_art_pieces_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_pieces',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
