# Generated by Django 3.2.5 on 2021-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_art_pieces_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_pieces',
            name='category',
            field=models.CharField(choices=[('PPLE', 'People'), ('OBJCT', 'Objects'), ('ABST', 'Abstract'), ('BUIL', 'Buildings'), ('LOCA', 'Location'), ('ANIM', 'Animal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='art_pieces',
            name='desc',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='Artwork_Cat',
        ),
    ]
