# Generated by Django 3.2.5 on 2021-07-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_date', models.DateTimeField(verbose_name='Purchase Date')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='directory.customer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='directory.artist')),
            ],
        ),
    ]
