# Generated by Django 3.2.5 on 2021-07-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_comment_rate'),
        ('directory', '0002_auto_20210714_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
